language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  allow_failures:
    - python: "3.8"

notifications:
  email: false

install:
  - pip install -e .[testing]
  - pip install coveralls

script: nosetests --with-coverage --cover-package=wilson

after_success: coveralls
